### ISSUE TITLE
Package names containing "_" character mangled incorrectly.

### ISSUE THREAD

**Issue by vi** [kawamuray/javah4x#1]
E.g. `org.vi_server` package gets `Java_org_vi_server` symbols, but should get `Java_org_vi_1server`.

**Comment by kawamuray** [comment]
Thanks, indeed I haven't implemented this w/ fully complying JNI's mangling rule. I've fixed it by #2 , not only for underscores but also for `;`, `[` and overloaded methods referring https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html (except that for multibyte characters)
